name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  checks: write
  actions: write
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # ============= InvisiRisk Setup =============
      - name: Setup PSE
        uses: invisirisk/pse-action@latest
        with:
          app_token: ${{secrets.IR_API_KEY}}
      # ============= InvisiRisk Setup End =============

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.0"
          bundler-cache: true

      - name: Run tests
        run: bundle exec rspec

     # ============= InvisiRisk Cleanup =============
      - name: Cleanup PSE
        if: always()
        uses: invisirisk/pse-action@latest
        with:
          cleanup: "true"
      # ============= InvisiRisk Cleanup End =============   

  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      checks: read
      actions: read
      packages: write

    steps:
      # ============= InvisiRisk Setup =============
      - name: Setup PSE
        uses: invisirisk/pse-action@latest
        with:
          app_token: ${{secrets.IR_API_KEY}}
      # ============= InvisiRisk Setup End =============

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          build-args: |
            BUILDKIT_SYNTAX=public.ecr.aws/w3c0c0n7/invisirisk/baf-buildkit:latest
            PSE_PROXY=http://${{ env.PSE_PROXY_IP }}:3128
          secret-files: |
            pse-ca=/etc/ssl/certs/pse.pem

              # ============= InvisiRisk Cleanup =============
      - name: Cleanup PSE
        if: always()
        uses: invisirisk/pse-action@latest
        with:
          cleanup: "true"
      # ============= InvisiRisk Cleanup End =============    

        
